- pages/validators/running_full_node.md
Follow-up for https://github.com/dydxprotocol/v4-chain/pull/282
> [CORE-535] [CLOB-878] - Update full node page to document the flag requirement for disabling gRPC

- pages/integration_docs/indexer_usage_estimates.md
> Adjust indexer estimates.

- pages/validators/preparing_for_genesis.md
- pages/validators/running_full_node.md
- pages/validators/starting_the_network.md
Left some fields / places as `TODO` since we will know these values later.
> Update validator prep + start docs testnet #4

- pages/integration_docs/composite_client.mdx
- pages/integration_docs/indexer_client.mdx
- pages/integration_docs/socket_client.mdx
- pages/integration_docs/validator_client.mdx
- pages/testnets/faucet.mdx
> Change dydx4 to v4-client-py (for pip command) or v4_client_py (module name in python)

- pages/networks/network1/resources.md
Remove DSRV / Nodefleet as they have turned down their nodes. Add Enigma, Lavendar Five and Polkachu.
> Update test-net RPC nodes.

- pages/governance/proposing_a_new_market.md
added explanation for how to select oracle sources and liquidity tier while proposing a new market
> adding to new market proposal documentation

- pages/governance/proposing_a_new_market.md
Adding a csv of example markets with robust oracles.
> add csvs of example markets

- pages/governance/proposing_a_new_market.md
* add explanation of the parameters
* add legal disclaimer
> update market proposal gov documentation

- pages/_meta.json
- pages/getting_started/Getting_started.md
- pages/trading/Rewards_and_Parameters.md
- pages/trading/_meta.json
Adding getting started and Lawrence's guides
> Add Getting Started and Lawrence's guides

- pages/developers/indexer/indexer_websocket.md
- pages/network/resources.mdx
- Fix "Lavendar" typos
- Remove confusing `### H3` titles which showed up in the sidebar
> Chore: Small cleanup on network resources page

- pages/guides/_meta.json
- pages/guides/running_a_full_node.md
Adds info on the following
1. Full node remains synced with latest state of blockchain
2. Pruning settings to reduce storage and compute requirements
3. How to connect to healthy peer
> [OTE-252] Add guide on running a full node

- pages/developers/clients/validator_client.mdx
Add new section to `ValidatorClient` documentation.
> Add documentation on selecting gas token used in transactions

- pages/api_trading.md
Adding info on querying/streaming block height and short-term orders
> fill in some info on docs

- pages/network/resources.mdx
A non-state breaking change that primarily includes performance improvements that significantly increase maximum order throughput.
> Add v4.1.2 to Upgrades History

- pages/validators/full_node_streaming.md
Add documentation on the buffered channel, startup flags, metrics, and some QA
> Add documentation for grpc streaming v4.1.4

- next.config.js
> Add redirects

- pages/infrastructure_providers-validators/running_a_validator.md
- pages/infrastructure_providers-validators/upgrades/upgrading_sidecar.md
- pages/introduction-onboarding_faqs.mdx
we recently updated our docs. this PR fixes the links!
> docs: update new links

- pages/infrastructure_providers-network/resources.mdx
- pages/infrastructure_providers-validators/_meta.json
- pages/infrastructure_providers-validators/how_to_set_up_full_node.md
- pages/infrastructure_providers-validators/running_full_node.md
This PR:
- Removes a lot of duplicated information from Set Up a Full Node
- Ties these pages together with links, standardizes titles and tenses
- Rewrites for clarity
- Adds persistent peer example
Please review for accuracy. Also, I left 4 comments on areas to check/ expand on with more info
> Run a full node update

- pages/infrastructure_providers-network/resources.mdx
fixes https://github.com/dydxprotocol/v4-documentation/issues/233
> fix mintscan link

- pages/users-governance/_meta.json
- pages/users-governance/functionalities.md
- pages/users-governance/proposing_a_new_market.md
- pages/users-governance/reading_new_market_proposal.md
Adds a page on interpreting a new market proposal JSON document
Intent is mostly for market makers to create programmatic trading software. Users may find it useful to better understand new markets
> Read a Market Proposal doc [CT-953]

- pages/users-governance/submitting_a_proposal.md
- pages/users-governance/voting.md
Command has been stale since v4 upgrade
> Update command for `dydxprotocold config` 

- pages/concepts-trading/margin.md
The current margining docs is verbose and outdated. Simplify and add documentation on OIMF.
> Update stale margining doc and add OIMF

- pages/infrastructure_providers-network/resources.mdx
Add URLs for Enigma's services for mainnet, as part of a DEP grant.
> Add enigma's mainnet services

- pages/infrastructure_providers-network/resources.mdx
Remove mainnet and testnet services fro network resources.
> Remove bware labs services

- pages/_app.tsx
- pages/concepts-architecture/architectural_overview.md
- pages/introduction-trading_fees.md
> Add GA tracking

- pages/infrastructure_providers-network/resources.mdx
Removing unresponsive seed nodes.
> fix: Update testnet seed nodes

- pages/infrastructure_providers-network/resources.mdx
Redone PR with signed commit as requested.
> Add Silk Nodes

- pages/user-guides/how_to_troubleshoot_withdrawals_and_deposits.md
- Lowered eth fees to 2.5
- arb support
> Eth fees 2.5 and added arbitrum support

- pages/infrastructure_providers-network/resources.mdx
Updated http to https and 23890 to 443 for Polkachu
> Update resources.mdx for Lawrence

- vocs-docs/docs/pages/indexer-client/http/accounts/get_funding_payments.mdx
- vocs-docs/docs/pages/indexer-client/http/accounts/get_funding_payments_for_parent_subaccount.mdx
- vocs-docs/docs/pages/indexer-client/http/accounts/index.mdx
- vocs-docs/docs/pages/types/funding_payment_response_object.mdx
- vocs-docs/docs/pages/types/funding_payments_response_object.mdx
Added funding payments to voc-docs
- getFundingPayments endpoint 
- getParentSubaccount endpoint
> Added funding payments to voc-docs

- vocs-docs/docs/pages/interaction/endpoints.mdx
Closes https://github.com/dydxprotocol/v4-documentation/issues/370
> fix: add missing comma
